-- MySQL Script generated by MySQL Workbench
-- Sun Apr 26 17:38:04 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema my_alert
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema my_alert
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `my_alert` DEFAULT CHARACTER SET utf8 ;
USE `my_alert` ;

-- -----------------------------------------------------
-- Table `my_alert`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_alert`.`User` (
  `idUser` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(70) NOT NULL,
  `BirthDate` DATETIME NOT NULL,
  `Sex` VARCHAR(1) NOT NULL,
  `Adress` VARCHAR(70) NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `Country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC) VISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `my_alert`.`Manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_alert`.`Manager` (
  `idManager` INT(11) NOT NULL AUTO_INCREMENT,
  `idUser_FK` INT(11) NOT NULL,
  `StartDate_task` DATETIME NOT NULL,
  `EndDate_task` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`idManager`),
  INDEX `fk_Manager_User1_idx` (`idUser_FK` ASC) VISIBLE,
  CONSTRAINT `fk_Manager_User1`
    FOREIGN KEY (`idUser_FK`)
    REFERENCES `my_alert`.`User` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `my_alert`.`Agent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_alert`.`Agent` (
  `idAgent` INT(11) NOT NULL AUTO_INCREMENT,
  `idUser_FK` INT(11) NOT NULL,
  `Department` VARCHAR(45) NOT NULL,
  `Department_Code` VARCHAR(10) NOT NULL,
  `Lat` VARCHAR(15) NULL DEFAULT NULL,
  `Lon` VARCHAR(15) NULL DEFAULT NULL,
  `StartDate_tsk` DATETIME NULL DEFAULT NULL,
  `EndDate_task` DATETIME NULL DEFAULT NULL,
  `idManager_FK` INT(11) NOT NULL,
  PRIMARY KEY (`idAgent`),
  INDEX `fk_Agent_User1_idx` (`idUser_FK` ASC) VISIBLE,
  INDEX `fk_Agent_Manager1_idx` (`idManager_FK` ASC) VISIBLE,
  CONSTRAINT `fk_Agent_Manager1`
    FOREIGN KEY (`idManager_FK`)
    REFERENCES `my_alert`.`Manager` (`idManager`),
  CONSTRAINT `fk_Agent_User1`
    FOREIGN KEY (`idUser_FK`)
    REFERENCES `my_alert`.`User` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `my_alert`.`Citizen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_alert`.`Citizen` (
  `idCitizen` INT(11) NOT NULL AUTO_INCREMENT,
  `idUser_FK` INT(11) NOT NULL,
  `Lat` VARCHAR(15) NULL DEFAULT NULL,
  `Long` VARCHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`idCitizen`),
  INDEX `fk_Citizen_User1_idx` (`idUser_FK` ASC) VISIBLE,
  CONSTRAINT `fk_Citizen_User1`
    FOREIGN KEY (`idUser_FK`)
    REFERENCES `my_alert`.`User` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `my_alert`.`Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_alert`.`Type` (
  `idType` INT(11) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `idManager` INT(11) NOT NULL,
  PRIMARY KEY (`idType`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE,
  UNIQUE INDEX `type_Name_IX` (`Name` ASC) VISIBLE,
  INDEX `fk_Type_Manager1_idx` (`idManager` ASC) VISIBLE,
  CONSTRAINT `fk_Type_Manager1`
    FOREIGN KEY (`idManager`)
    REFERENCES `my_alert`.`Manager` (`idUser_FK`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `my_alert`.`Intervention`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_alert`.`Intervention` (
  `idIntervation` INT(11) NOT NULL,
  `Type` VARCHAR(45) NOT NULL,
  `Lat` VARCHAR(15) NOT NULL,
  `Long` VARCHAR(15) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `StartDate` DATETIME NULL DEFAULT NULL,
  `EndDate` DATETIME NULL DEFAULT NULL,
  `ShortReport` MEDIUMTEXT NULL DEFAULT NULL,
  `DetailedReport` LONGTEXT NULL DEFAULT NULL,
  `Status` VARCHAR(45) NOT NULL DEFAULT 'signaled',
  PRIMARY KEY (`idIntervation`),
  INDEX `fk_Alarm_Type1_idx` (`Type` ASC) VISIBLE,
  CONSTRAINT `fk_Alarm_Type1`
    FOREIGN KEY (`Type`)
    REFERENCES `my_alert`.`Type` (`Name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `my_alert`.`Alarm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_alert`.`Alarm` (
  `idAlarm` VARCHAR(45) NOT NULL,
  `idCitizen` INT(11) NOT NULL,
  `idIntervation` INT(11) NOT NULL,
  `AlarmDate` TIMESTAMP(6) NULL DEFAULT NULL,
  PRIMARY KEY (`idAlarm`),
  INDEX `fk_Citizen_has_Intervention_Intervention1_idx` (`idIntervation` ASC) VISIBLE,
  INDEX `fk_Citizen_has_Intervention_Citizen1_idx` (`idCitizen` ASC) VISIBLE,
  CONSTRAINT `fk_Citizen_has_Intervention_Citizen1`
    FOREIGN KEY (`idCitizen`)
    REFERENCES `my_alert`.`Citizen` (`idUser_FK`),
  CONSTRAINT `fk_Citizen_has_Intervention_Intervention1`
    FOREIGN KEY (`idIntervation`)
    REFERENCES `my_alert`.`Intervention` (`idIntervation`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `my_alert`.`Assign`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_alert`.`Assign` (
  `idAssign` INT(11) NOT NULL,
  `idManager` INT(11) NOT NULL,
  `idAgent` INT(11) NOT NULL,
  `Confirm` TINYINT(4) NOT NULL DEFAULT '0',
  `HasWritten` TINYINT(4) NOT NULL DEFAULT '0',
  `Start_validate` DATETIME NULL DEFAULT NULL,
  `End_validate` DATETIME NULL DEFAULT NULL,
  `idIntervation` INT(11) NOT NULL,
  PRIMARY KEY (`idAssign`),
  INDEX `fk_Assign_Manager1_idx` (`idManager` ASC) VISIBLE,
  INDEX `fk_Assign_Agent1_idx` (`idAgent` ASC) VISIBLE,
  INDEX `fk_Assign_Intervention1_idx` (`idIntervation` ASC) VISIBLE,
  CONSTRAINT `fk_Assign_Agent1`
    FOREIGN KEY (`idAgent`)
    REFERENCES `my_alert`.`Agent` (`idUser_FK`),
  CONSTRAINT `fk_Assign_Intervention1`
    FOREIGN KEY (`idIntervation`)
    REFERENCES `my_alert`.`Intervention` (`idIntervation`),
  CONSTRAINT `fk_Assign_Manager1`
    FOREIGN KEY (`idManager`)
    REFERENCES `my_alert`.`Manager` (`idUser_FK`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `my_alert`.`Image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_alert`.`Image` (
  `idImage` INT(11) NOT NULL AUTO_INCREMENT,
  `Url` VARCHAR(70) NOT NULL,
  `Lat` VARCHAR(15) NULL DEFAULT NULL,
  `Long` VARCHAR(15) NULL DEFAULT NULL,
  `idUser` INT(11) NOT NULL,
  `idIntervation` INT(11) NOT NULL,
  PRIMARY KEY (`idImage`),
  INDEX `fk_Image_User1_idx` (`idUser` ASC) VISIBLE,
  INDEX `fk_Image_Intervention1_idx` (`idIntervation` ASC) VISIBLE,
  CONSTRAINT `fk_Image_Intervention1`
    FOREIGN KEY (`idIntervation`)
    REFERENCES `my_alert`.`Intervention` (`idIntervation`),
  CONSTRAINT `fk_Image_User1`
    FOREIGN KEY (`idUser`)
    REFERENCES `my_alert`.`User` (`idUser`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
